"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 21:45:27.183506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CREATE_TENANT_FUNCTION = """
CREATE FUNCTION app_current_tenant() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$
"""

RLS_STATEMENTS = [
    "ALTER TABLE tenants ENABLE ROW LEVEL SECURITY",
    "CREATE POLICY tenant_isolation ON tenants FOR SELECT USING (id = app_current_tenant())",
    "ALTER TABLE users ENABLE ROW LEVEL SECURITY",
    """
    CREATE POLICY tenant_isolation ON users
        USING (tenant_id = app_current_tenant())
        WITH CHECK (tenant_id = app_current_tenant())
    """,
    "ALTER TABLE documents ENABLE ROW LEVEL SECURITY",
    """
    CREATE POLICY tenant_isolation ON documents
        USING (tenant_id = app_current_tenant())
        WITH CHECK (tenant_id = app_current_tenant())
    """,
]


def upgrade() -> None:
    """Upgrade schema."""

    op.execute(CREATE_TENANT_FUNCTION)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='users_role_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('status', sa.Text(), server_default='uploaded', nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('quote', 'rate_sheet', 'invoice', 'unknown')", name='documents_doc_type_check'),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'needs_review', 'processed', 'failed')", name='documents_status_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('documents_tenant_created_idx', 'documents', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    for statement in RLS_STATEMENTS:
      op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('documents_tenant_created_idx', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION app_current_tenant()")
